'use strict';

const express = require('express');
const bearerMiddleware = require('./middleware/bearer');
const User = require('./models/users-model');

const extraRouter = express.Router();

extraRouter.get('/secret', bearerMiddleware, secret );


/**
 * @route POST /signup creates an individual user object and adds it to the Users database
 * @param {user_request} user.body.required - the new user
 * @returns {token} 200 - a token generated by a generateToken method
 * @returns {Error} 500 - unexpected error
 */

async function secret(req, res, next) {
  res.json({ bearer:'valid',user:req.user });

}


module.exports = extraRouter;


